"use client";
import {useCallback,useEffect,useMemo,useState} from "react";
import {apiFetch,getUserIdHeader} from "@/lib/api";
import {formatTHB} from "@/lib/utils/formatters";
import {useMe} from "@/lib/roles";
import type {Lead,Package} from "./types";

type Item={id?:number;source_type:"package"|"addon"|"custom";item_name?:string;item_name_snapshot?:string;quantity:number;unit:string;unit_price:number};
type Quote={id:number;option_no:number;doc_no:string;revision_no:number;status:string;package_id:number;package_name_snapshot:string;package_price_snapshot:number;contract_total_incl_vat:number;deposit_paid_amount:number;outstanding_amount:number;discount_label?:string;discount_type:string;discount_value:number;discount_reason?:string;payment_template_id?:number;payment_terms_json:string;terms_text?:string;note?:string;approval_note?:string;items:Item[]};
type Template={id:number;name:string;is_default:boolean;terms:Array<{label:string;percent:number;due:string}>};
const statusLabel:Record<string,string>={draft:"ฉบับร่าง",pending_approval:"รออนุมัติ",approved:"อนุมัติแล้ว",changes_required:"ส่งกลับแก้ไข"};
const emptyItem=():Item=>({source_type:"custom",item_name:"",quantity:1,unit:"ชุด",unit_price:0});

export default function QuotationBuilder({lead,packages,refresh}:{lead:Lead;packages:Package[];refresh:()=>Promise<unknown>|void}){
  const {me}=useMe();const [quotes,setQuotes]=useState<Quote[]>([]);const [templates,setTemplates]=useState<Template[]>([]);const [editing,setEditing]=useState<number|null>(null);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
  const confirmedDeposit=lead.payment_confirmed?Math.max(0,Number(lead.pre_total_price)||0):0;
  const load=useCallback(async()=>{try{setQuotes(await apiFetch(`/api/leads/${lead.id}/quotations`));}catch(e){setError(e instanceof Error?e.message:"โหลดใบเสนอราคาไม่สำเร็จ");}},[lead.id]);
  useEffect(()=>{load();apiFetch("/api/quotation-templates").then(setTemplates).catch(()=>undefined);},[load]);
  const latest=useMemo(()=>{const map=new Map<number,Quote>();for(const q of quotes)if(!map.has(q.option_no))map.set(q.option_no,q);return map;},[quotes]);
  const currentQuotes=useMemo(()=>Array.from(latest.values()),[latest]);
  const readyQuotes=currentQuotes.filter(q=>["draft","changes_required"].includes(q.status));
  const act=async(id:number,action:string,note="")=>{setBusy(true);setError("");try{await apiFetch(`/api/quotations/${id}/action`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,note})});await load();await refresh();}catch(e){setError(e instanceof Error?e.message:"ดำเนินการไม่สำเร็จ");}finally{setBusy(false);}};
  const openPdf=async(id:number,download=false)=>{try{const response=await fetch(`/api/quotation-pdf/${id}${download?"?download=1":""}`,{headers:{...getUserIdHeader()}});if(!response.ok)throw new Error("เปิด PDF ไม่สำเร็จ");const blob=await response.blob();const url=URL.createObjectURL(blob);window.open(url,"_blank","noopener,noreferrer");setTimeout(()=>URL.revokeObjectURL(url),60000);}catch(e){setError(e instanceof Error?e.message:"เปิด PDF ไม่สำเร็จ");}};
  const submitAll=async()=>{if(!readyQuotes.length)return;setBusy(true);setError("");try{for(const q of readyQuotes)await apiFetch(`/api/quotations/${q.id}/action`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"submit"})});await load();await refresh();}catch(e){setError(e instanceof Error?e.message:"ส่งขออนุมัติไม่สำเร็จ");}finally{setBusy(false);}};
  return <div className="space-y-3">
    <div className="flex items-center justify-between gap-3"><div><div className="text-xs font-bold uppercase tracking-wide text-gray-500">ใบเสนอราคา <span className="font-normal normal-case text-gray-400">(สูงสุด 3 ฉบับ — ลูกค้าจะเลือก 1 ฉบับใน Order step)</span> <span className="text-red-500">*</span></div></div><div className="text-xxs text-gray-400 text-right">เลือกฉบับที่จะส่งให้ลูกค้าได้มากกว่า 1 ฉบับ</div></div>
    {error&&<div className="rounded-lg bg-red-50 border border-red-200 px-3 py-2 text-xs text-red-700">{error}</div>}
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-3">{[1,2,3].map(option=>{const q=latest.get(option);const pkg=q?packages.find(p=>p.id===q.package_id):null;const extras=q?.items.filter(i=>i.source_type!=="package")||[];return q?<article key={option} className="rounded-xl border border-gray-200 bg-white p-4 min-h-[342px] flex flex-col shadow-sm">
      <div className="flex items-start gap-3"><div className="w-8 h-8 rounded-lg bg-gradient-to-br from-primary to-cyan-400 text-white flex items-center justify-center shrink-0"><svg className="w-4 h-4" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M5 12l4 4L19 6"/></svg></div><div className="min-w-0 flex-1"><div className="font-bold text-sm text-gray-900">ชุด {option}</div><div className="text-xxs text-gray-400 font-mono mt-0.5 truncate">{q.doc_no}{q.revision_no>0?` · Rev.${q.revision_no}`:""}</div></div><span className={`text-xxs px-2.5 py-1 rounded-full font-semibold whitespace-nowrap ${q.status==="approved"?"bg-emerald-50 text-emerald-700":q.status==="pending_approval"?"bg-amber-50 text-amber-700":q.status==="changes_required"?"bg-red-50 text-red-700":"bg-violet-50 text-violet-700"}`}>{statusLabel[q.status]}</span></div>
      <div className="mt-4 rounded-xl border border-gray-200 bg-gray-50/70 p-3"><div className="text-xxs font-semibold text-gray-400">แพ็กเกจหลัก</div><div className="mt-1 font-bold text-sm text-gray-900 line-clamp-2">{q.package_name_snapshot}</div><div className="mt-1 text-xxs text-gray-500">{pkg?`${pkg.phase||"-"} เฟส · ${pkg.inverter_brand||"ไม่ระบุ Inverter"}${pkg.has_battery?` · Battery ${pkg.battery_kwh||""} kWh`:""}`:"Snapshot จาก Package Master"}</div></div>
      <div className="mt-2 min-h-8 flex flex-wrap content-start gap-1.5">{extras.length?extras.slice(0,3).map((item,index)=><span key={item.id||index} className="px-2 py-1 rounded-full bg-violet-50 text-violet-700 text-xxs">+ {item.item_name_snapshot||item.item_name}</span>):<span className="px-2 py-1 rounded-full bg-gray-100 text-gray-500 text-xxs">ไม่มี Add-on</span>}{extras.length>3&&<span className="px-2 py-1 rounded-full bg-violet-50 text-violet-700 text-xxs">+{extras.length-3} รายการ</span>}</div>
      {q.approval_note&&<div className="mt-2 text-xs text-red-600 line-clamp-2">เหตุผล: {q.approval_note}</div>}
      <div className="mt-auto pt-4 border-t border-gray-200 flex items-end justify-between"><span className="text-xxs text-gray-400">ยอดที่ต้องชำระ</span><div className="text-right"><b className="text-xl text-gray-900 tabular-nums">{formatTHB(q.outstanding_amount)}</b> <span className="text-xxs font-semibold">บาท</span></div></div>
      <div className="grid grid-cols-3 gap-2 mt-3">{["draft","changes_required"].includes(q.status)?<><button onClick={()=>setEditing(option)} className="h-9 rounded-lg border border-violet-300 bg-violet-50 text-violet-700 text-xs font-semibold">✎ แก้ไข</button><button onClick={()=>openPdf(q.id)} className="h-9 rounded-lg border border-gray-200 text-gray-700 text-xs font-semibold">▣ PDF</button><button disabled={busy} onClick={()=>act(q.id,"submit")} className="h-9 rounded-lg border border-gray-200 text-gray-700 text-xs font-semibold">ส่งอนุมัติ</button></>:q.status==="pending_approval"&&me?.roles.some(r=>["admin","sales_sup"].includes(r))?<><button onClick={()=>openPdf(q.id)} className="h-9 rounded-lg border border-gray-200 text-xs font-semibold">▣ PDF</button><button disabled={busy} onClick={()=>{const n=prompt("ระบุเหตุผลที่ส่งกลับแก้ไข");if(n)act(q.id,"changes_required",n);}} className="h-9 rounded-lg bg-red-50 text-red-700 text-xs font-semibold">ส่งกลับ</button><button disabled={busy} onClick={()=>act(q.id,"approve")} className="h-9 rounded-lg bg-emerald-600 text-white text-xs font-semibold">อนุมัติ</button></>:q.status==="approved"?<><button onClick={()=>openPdf(q.id)} className="h-9 rounded-lg border border-gray-200 text-xs font-semibold">▣ PDF</button><button disabled={busy} onClick={()=>act(q.id,"revise")} className="h-9 rounded-lg border border-gray-200 text-xs font-semibold">Revision</button><button disabled={busy} onClick={()=>act(q.id,"mark_sent")} className="h-9 rounded-lg bg-primary text-white text-xs font-semibold">ส่งลูกค้า</button></>:<><button onClick={()=>openPdf(q.id)} className="col-span-3 h-9 rounded-lg border border-gray-200 text-xs font-semibold">▣ ดู PDF</button></>}</div>
    </article>:<article key={option} className="rounded-xl border border-dashed border-violet-300 bg-white/40 min-h-[342px] p-5 flex flex-col items-center justify-center text-center"><div className="w-16 h-16 rounded-2xl bg-violet-100 text-violet-600 flex items-center justify-center text-4xl font-light">+</div><h3 className="mt-3 text-base font-bold text-gray-900">สร้างใบเสนอราคาชุดที่ {option}</h3><p className="mt-1 text-xs text-gray-400">เลือกแพ็กเกจหลักและ Add-on สำหรับใบเสนอราคาชุดนี้</p><button onClick={()=>setEditing(option)} className="mt-5 h-10 px-5 rounded-lg bg-violet-600 hover:bg-violet-700 text-white text-xs font-semibold">+ สร้างใบเสนอราคา</button></article>})}</div>
    <div className="rounded-xl border border-violet-200 bg-white p-4 flex flex-col md:flex-row md:items-center gap-3"><div className="w-10 h-10 rounded-xl bg-violet-100 text-violet-600 flex items-center justify-center text-xl shrink-0">✓</div><div className="flex-1"><div className="text-sm font-bold text-gray-900">{currentQuotes.length?`มีใบเสนอราคา ${currentQuotes.length} ฉบับ`:`ยังไม่มีใบเสนอราคา`}</div><div className="text-xs text-gray-400 mt-0.5">{readyQuotes.length?`${readyQuotes.map(q=>`ชุด ${q.option_no}`).join(" และ ")} พร้อมส่งขออนุมัติ · ลูกค้าจะเลือก 1 ฉบับในขั้น Order`:"สร้างฉบับร่างจาก Package Master เพื่อเริ่มต้น"}</div></div><div className="text-xs text-gray-500 whitespace-nowrap"><b className="text-gray-800">{currentQuotes.length}</b>/3 ฉบับ</div></div>
    <div><label className="text-xs font-semibold tracking-wider uppercase text-gray-400 block mb-1">ผู้จัดทำ</label><input type="text" value={me?.full_name||""} readOnly className="w-full h-11 px-3 rounded-lg border border-gray-200 bg-white text-sm text-gray-700" /></div>
    {currentQuotes.length>0&&<div className="grid grid-cols-1 md:grid-cols-[220px_1fr] gap-2"><button onClick={()=>currentQuotes[0]&&openPdf(currentQuotes[0].id)} className="h-11 rounded-lg border border-primary bg-cyan-50/60 text-primary text-sm font-semibold">▣ สร้าง PDF ที่เลือก</button><button disabled={busy||readyQuotes.length===0} onClick={submitAll} className="h-11 rounded-lg bg-gradient-to-r from-primary to-cyan-500 text-white text-sm font-semibold disabled:opacity-40">▷ ส่งขออนุมัติใบเสนอราคา{readyQuotes.length>1?` ${readyQuotes.length} ฉบับ`:""}</button></div>}
    {editing!==null&&<QuotationEditor optionNo={editing} quote={latest.get(editing)} packages={packages} templates={templates} leadId={lead.id} confirmedDeposit={confirmedDeposit} onClose={()=>setEditing(null)} onSaved={async()=>{setEditing(null);await load();}}/>}
  </div>;
}

function QuotationEditor({optionNo,quote,packages,templates,leadId,confirmedDeposit,onClose,onSaved}:{optionNo:number;quote?:Quote;packages:Package[];templates:Template[];leadId:number;confirmedDeposit:number;onClose:()=>void;onSaved:()=>Promise<void>}){
  const defaultTemplate=templates.find(t=>t.is_default)||templates[0];const [packageId,setPackageId]=useState(quote?.package_id||packages[0]?.id||0);const [packageItems,setPackageItems]=useState<Item[]>([]);const [items,setItems]=useState<Item[]>(quote?.items?.filter(i=>i.source_type!=="package").map(i=>({...i,item_name:i.item_name_snapshot||i.item_name}))||[]);
  const [discountType,setDiscountType]=useState(quote?.discount_type||"amount");const [discountValue,setDiscountValue]=useState(Number(quote?.discount_value)||0);const [discountLabel,setDiscountLabel]=useState(quote?.discount_label||"");const [discountReason,setDiscountReason]=useState(quote?.discount_reason||"");const [deposit,setDeposit]=useState(Math.max(Number(quote?.deposit_paid_amount)||0,confirmedDeposit));const [templateId,setTemplateId]=useState<number|undefined>(quote?.payment_template_id||defaultTemplate?.id);const [terms,setTerms]=useState(()=>{try{return quote?JSON.parse(quote.payment_terms_json):defaultTemplate?.terms||[];}catch{return defaultTemplate?.terms||[];}});const [note,setNote]=useState(quote?.note||"");const [termsText,setTermsText]=useState(quote?.terms_text||"");const [saving,setSaving]=useState(false);const [error,setError]=useState("");
  useEffect(()=>{if(!packageId){setPackageItems([]);return;}apiFetch(`/api/packages/${packageId}/items`).then((rows:Item[])=>setPackageItems(rows)).catch(()=>setPackageItems([]));},[packageId]);
  useEffect(()=>{if(quote||terms.length||!defaultTemplate)return;setTemplateId(defaultTemplate.id);setTerms(defaultTemplate.terms);},[defaultTemplate,quote,terms.length]);
  const pkg=packages.find(p=>p.id===packageId);const extras=items.reduce((s,i)=>s+(Number(i.quantity)||0)*(Number(i.unit_price)||0),0);const subtotal=Number(pkg?.price||0)+extras;const discount=discountType==="percent"?subtotal*Math.min(discountValue,100)/100:Math.min(discountValue,subtotal);const total=Math.max(0,subtotal-discount);const outstanding=Math.max(0,total-deposit);
  const updateItem=(idx:number,patch:Partial<Item>)=>setItems(v=>v.map((i,n)=>n===idx?{...i,...patch}:i));
  const save=async()=>{if(!packageId){setError("กรุณาเลือก Package หลัก");return;}setSaving(true);setError("");try{const payload={option_no:optionNo,package_id:packageId,items,discount_type:discountType,discount_value:discountValue,discount_label:discountLabel,discount_reason:discountReason,deposit_paid_amount:deposit,payment_template_id:templateId,payment_terms:terms,terms_text:termsText,note};await apiFetch(quote?`/api/quotations/${quote.id}`:`/api/leads/${leadId}/quotations`,{method:quote?"PATCH":"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});await onSaved();}catch(e){setError(e instanceof Error?e.message:"บันทึกไม่สำเร็จ");}finally{setSaving(false);}};
  const fieldClass="min-h-[46px] w-full rounded-lg border border-gray-200 bg-white px-3 py-2 text-sm text-gray-800 outline-none transition-colors placeholder:text-gray-300 hover:border-gray-300 focus:border-primary focus:ring-2 focus:ring-primary/10";
  const compactFieldClass="min-h-[46px] w-full rounded-lg border border-gray-200 bg-white px-2.5 py-2 text-xs text-gray-800 outline-none transition-colors placeholder:text-gray-300 hover:border-gray-300 focus:border-primary focus:ring-2 focus:ring-primary/10";
  return <div className="fixed inset-0 z-[80] overflow-y-auto bg-slate-900/35 p-3 backdrop-blur-[1px] md:p-8"><div className="mx-auto max-w-4xl overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-2xl shadow-slate-900/20"><div className="sticky top-0 z-10 flex items-center justify-between border-b border-gray-200 bg-gradient-to-r from-white via-white to-primary/5 p-4"><div><b className="text-sm text-gray-900">ใบเสนอราคา ชุด {optionNo}</b><div className="mt-0.5 text-xs text-gray-500">{quote?`แก้ไข ${quote.doc_no}`:"เลขเอกสารจะสร้างอัตโนมัติ SM-QT-YY-XXXX"}</div></div><button type="button" onClick={onClose} aria-label="ปิด" className="flex h-8 w-8 items-center justify-center rounded-lg text-xl text-gray-400 transition-colors hover:bg-gray-100 hover:text-gray-700">×</button></div><div className="space-y-5 bg-white p-4 md:p-5">
    {error&&<div className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
    <section><label className="text-xs font-semibold text-gray-500">Package หลัก</label><select value={packageId} onChange={e=>setPackageId(Number(e.target.value))} className={`mt-1 ${fieldClass}`}><option value={0}>เลือก Package</option>{packages.map(p=><option key={p.id} value={p.id}>{p.name} — {formatTHB(p.price)} บาท</option>)}</select>{packageItems.length>0?<div className="mt-2 rounded-xl border border-primary/15 bg-primary/5 p-3"><div className="mb-1 text-xs font-bold text-primary">อุปกรณ์หลักจาก Package (แก้ไขไม่ได้)</div>{packageItems.map((i,n)=><div key={i.id||n} className="py-0.5 text-xs text-gray-700">• {i.item_name_snapshot||i.item_name} {i.quantity} {i.unit}</div>)}</div>:<div className="mt-2 rounded-lg border border-amber-200 bg-amber-50 p-2 text-xs text-amber-700">Package นี้ยังไม่มีรายการอุปกรณ์ใน Master — ระบบยังคงใช้ชื่อและราคาหลักของ Package</div>}</section>
    <section><div className="flex items-center justify-between"><label className="text-xs font-semibold text-gray-500">ตัวเลือกเพิ่มเติม / รายการพิเศษ</label><button type="button" onClick={()=>setItems(v=>[...v,emptyItem()])} className="rounded-lg border border-primary/20 bg-primary/5 px-2.5 py-1.5 text-xs font-semibold text-primary transition-colors hover:bg-primary/10">+ Add เสริม</button></div><div className="mt-2 space-y-2">{items.map((i,n)=><div key={n} className="grid grid-cols-12 items-center gap-2 rounded-xl border border-gray-100 bg-gray-50/70 p-2"><select value={i.source_type} onChange={e=>updateItem(n,{source_type:e.target.value as "addon"|"custom"})} className={`col-span-2 ${compactFieldClass}`}><option value="addon">Add-on</option><option value="custom">รายการอื่น</option></select><input value={i.item_name||""} onChange={e=>updateItem(n,{item_name:e.target.value})} placeholder="ชื่ออุปกรณ์/บริการ" className={`col-span-4 ${compactFieldClass}`}/><input type="number" value={i.quantity} onChange={e=>updateItem(n,{quantity:Number(e.target.value)})} className={`col-span-2 ${compactFieldClass}`}/><input type="number" value={i.unit_price} onChange={e=>updateItem(n,{unit_price:Number(e.target.value)})} placeholder="ราคา/หน่วย" className={`col-span-3 ${compactFieldClass}`}/><button type="button" onClick={()=>setItems(v=>v.filter((_,x)=>x!==n))} aria-label="ลบรายการ" className="col-span-1 flex h-8 items-center justify-center rounded-lg text-red-400 transition-colors hover:bg-red-50 hover:text-red-600">×</button></div>)}</div></section>
    <section className="grid gap-3 md:grid-cols-2"><div><label className="text-xs font-semibold text-gray-500">ชื่อส่วนลด</label><input value={discountLabel} onChange={e=>setDiscountLabel(e.target.value)} placeholder="เช่น ส่วนลดพิเศษ VIP" className={`mt-1 ${fieldClass}`}/></div><div className="grid grid-cols-2 gap-2"><div><label className="text-xs font-semibold text-gray-500">ประเภทส่วนลด</label><select value={discountType} onChange={e=>setDiscountType(e.target.value)} className={`mt-1 ${fieldClass}`}><option value="amount">จำนวนเงิน</option><option value="percent">เปอร์เซ็นต์</option></select></div><div><label className="text-xs font-semibold text-gray-500">มูลค่าส่วนลด</label><input type="number" value={discountValue} onChange={e=>setDiscountValue(Number(e.target.value))} className={`mt-1 ${fieldClass}`}/></div></div><div><label className="text-xs font-semibold text-gray-500">เหตุผลส่วนลด</label><input value={discountReason} onChange={e=>setDiscountReason(e.target.value)} className={`mt-1 ${fieldClass}`}/></div><div><label className="text-xs font-semibold text-gray-500">ค่าสำรวจ/เงินจองที่ชำระแล้ว</label><input type="number" min={confirmedDeposit} value={deposit} onChange={e=>setDeposit(Math.max(confirmedDeposit,Number(e.target.value)||0))} className={`mt-1 ${fieldClass}`}/>{confirmedDeposit>0&&<p className="mt-1 text-xxs text-emerald-600">ดึงยอดที่ยืนยันรับเงินแล้วอัตโนมัติ {formatTHB(confirmedDeposit)} บาท</p>}</div></section>
    <section><label className="text-xs font-semibold text-gray-500">Template เงื่อนไขชำระเงิน</label><select value={templateId||""} onChange={e=>{const id=Number(e.target.value);setTemplateId(id);const t=templates.find(x=>x.id===id);if(t)setTerms(t.terms);}} className={`mt-1 ${fieldClass}`}>{templates.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><div className="mt-2 space-y-2">{terms.map((t:{label:string;percent:number;due:string},n:number)=><div key={n} className="grid grid-cols-12 gap-2"><input value={t.label} onChange={e=>setTerms((v:typeof terms)=>v.map((x:typeof t,i:number)=>i===n?{...x,label:e.target.value}:x))} className={`col-span-3 ${compactFieldClass}`}/><input type="number" value={t.percent} onChange={e=>setTerms((v:typeof terms)=>v.map((x:typeof t,i:number)=>i===n?{...x,percent:Number(e.target.value)}:x))} className={`col-span-2 ${compactFieldClass}`}/><input value={t.due} onChange={e=>setTerms((v:typeof terms)=>v.map((x:typeof t,i:number)=>i===n?{...x,due:e.target.value}:x))} className={`col-span-7 ${compactFieldClass}`}/></div>)}</div></section>
    <section className="grid gap-3 md:grid-cols-2"><textarea value={termsText} onChange={e=>setTermsText(e.target.value)} placeholder="เงื่อนไขเพิ่มเติม" rows={3} className={fieldClass}/><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="หมายเหตุในใบเสนอราคา" rows={3} className={fieldClass}/></section>
    <div className="grid grid-cols-2 gap-3 rounded-xl border border-gray-100 bg-gray-50/80 p-4 text-sm md:grid-cols-4"><div><small className="text-gray-400">Package</small><b className="mt-1 block text-gray-800">{formatTHB(pkg?.price||0)}</b></div><div><small className="text-gray-400">รวมก่อนลด</small><b className="mt-1 block text-gray-800">{formatTHB(subtotal)}</b></div><div><small className="text-gray-400">หักส่วนลด/ยอดชำระแล้ว</small><b className="mt-1 block text-red-500">-{formatTHB(discount+deposit)}</b></div><div><small className="text-gray-400">ยอดที่ต้องชำระ</small><b className="mt-1 block text-lg text-primary">{formatTHB(outstanding)}</b></div></div>
  </div><div className="sticky bottom-0 flex justify-end gap-2 border-t border-gray-200 bg-gray-50/90 p-4 backdrop-blur-sm"><button type="button" onClick={onClose} className="rounded-lg border border-gray-200 bg-white px-4 py-2 text-sm font-medium text-gray-600 transition-colors hover:bg-gray-100">ยกเลิก</button><button type="button" disabled={saving} onClick={save} className="rounded-lg bg-gradient-to-r from-primary to-cyan-500 px-5 py-2 text-sm font-semibold text-white shadow-sm transition-all hover:brightness-105 disabled:opacity-50">{saving?"กำลังบันทึก...":"บันทึกฉบับร่าง"}</button></div></div></div>;
}
