import { NextRequest,NextResponse } from "next/server";
import { getDb,sql } from "@/lib/db";
import { requireAuth } from "@/lib/auth";
import { getQuotationActor, nextQuotationDocNo } from "@/lib/quotation";
import { logLeadActivity } from "@/lib/lead-activity-log";
import { buildQuotationDocumentSnapshot, validateQuotationDocument } from "@/lib/quotation-document";

export async function POST(req:NextRequest,{params}:{params:Promise<{id:string}>}){
  const gate=await requireAuth(req);if(gate.error)return gate.error;const actor=await getQuotationActor(gate.userId);if(!actor)return NextResponse.json({error:"ไม่พบผู้ใช้"},{status:401});
  const {id}=await params;const quotationId=Number(id);const body=await req.json();const action=String(body.action||"");const note=String(body.note||"").trim();const db=await getDb();const tx=new sql.Transaction(db);
  try{await tx.begin();const found=await new sql.Request(tx).input("id",sql.Int,quotationId).query(`SELECT q.*,l.assigned_user_id FROM quotations q JOIN leads l ON l.id=q.lead_id WHERE q.id=@id`);const q=found.recordset[0];if(!q){await tx.rollback();return NextResponse.json({error:"ไม่พบใบเสนอราคา"},{status:404});}
    let next="";let createdRevisionId:number|null=null;
    if(action==="revise"){
      if(q.status!=="approved"){await tx.rollback();return NextResponse.json({error:"สร้าง Revision ได้เฉพาะใบที่อนุมัติแล้ว"},{status:409});}
      if(!actor.roles.includes("admin")&&q.assigned_user_id!==gate.userId){await tx.rollback();return NextResponse.json({error:"สร้าง Revision ได้เฉพาะผู้รับผิดชอบ Lead หรือ Admin"},{status:403});}
      const latest=await new sql.Request(tx).input("lead_id",sql.Int,q.lead_id).input("option",sql.Int,q.option_no).query(`SELECT MAX(revision_no) revision_no FROM quotations WITH (UPDLOCK,HOLDLOCK) WHERE lead_id=@lead_id AND option_no=@option`);
      if(Number(latest.recordset[0]?.revision_no)!==Number(q.revision_no)){await tx.rollback();return NextResponse.json({error:"มี Revision ใหม่กว่านี้แล้ว"},{status:409});}
      const newDocNo=await nextQuotationDocNo(tx);const inserted=await new sql.Request(tx).input("id",sql.Int,quotationId).input("doc",sql.NVarChar(30),newDocNo).input("uid",sql.Int,gate.userId).query(`INSERT quotations(lead_id,option_no,doc_no,revision_no,status,package_id,package_name_snapshot,package_price_snapshot,issue_date,valid_days,subtotal_incl_vat,discount_label,discount_type,discount_value,discount_amount,discount_reason,contract_total_incl_vat,deposit_paid_amount,outstanding_amount,vat_rate,amount_before_vat,vat_amount,payment_template_id,payment_terms_json,terms_text,note,document_inputs_json,created_by,updated_by) OUTPUT INSERTED.id SELECT lead_id,option_no,@doc,revision_no+1,'draft',package_id,package_name_snapshot,package_price_snapshot,CAST(GETDATE() AS DATE),valid_days,subtotal_incl_vat,discount_label,discount_type,discount_value,discount_amount,discount_reason,contract_total_incl_vat,deposit_paid_amount,outstanding_amount,vat_rate,amount_before_vat,vat_amount,payment_template_id,payment_terms_json,terms_text,note,document_inputs_json,@uid,@uid FROM quotations WHERE id=@id`);
      createdRevisionId=inserted.recordset[0].id;await new sql.Request(tx).input("old",sql.Int,quotationId).input("new",sql.Int,createdRevisionId).query(`INSERT quotation_items(quotation_id,source_type,package_item_id,item_name_snapshot,quantity,unit,unit_price,line_total,sort_order) SELECT @new,source_type,package_item_id,item_name_snapshot,quantity,unit,unit_price,line_total,sort_order FROM quotation_items WHERE quotation_id=@old`);next="draft";
    }else if(action==="submit"){
      if(!["draft","changes_required"].includes(q.status)){await tx.rollback();return NextResponse.json({error:"สถานะไม่สามารถส่งอนุมัติได้"},{status:409});}
      if(!actor.roles.includes("admin")&&q.assigned_user_id!==gate.userId){await tx.rollback();return NextResponse.json({error:"ส่งได้เฉพาะผู้รับผิดชอบ Lead"},{status:403});}next="pending_approval";
      const snapshot=await buildQuotationDocumentSnapshot(quotationId,tx);
      if(!snapshot){await tx.rollback();return NextResponse.json({error:"สร้างชุดข้อมูลเอกสารไม่สำเร็จ"},{status:500});}
      const validationErrors=validateQuotationDocument(snapshot);
      if(validationErrors.length){await tx.rollback();return NextResponse.json({error:`เอกสารยังไม่พร้อมส่งอนุมัติ: ${validationErrors.join(" · ")}`},{status:400});}
      await new sql.Request(tx).input("id",sql.Int,quotationId).input("uid",sql.Int,gate.userId).input("snapshot",sql.NVarChar(sql.MAX),JSON.stringify(snapshot)).input("financial",sql.NVarChar(sql.MAX),JSON.stringify(snapshot.financial)).query(`UPDATE quotations SET status='pending_approval',submitted_by=@uid,submitted_at=GETDATE(),document_snapshot_json=@snapshot,financial_snapshot_json=@financial,document_snapshot_at=GETDATE(),approval_note=NULL,approval_certified_by=NULL,approval_certified_at=NULL,updated_by=@uid,updated_at=GETDATE() WHERE id=@id`);
    }else if(action==="approve"){
      if(q.status!=="pending_approval"||!actor.roles.some((r:string)=>["admin","sales_sup"].includes(r))){await tx.rollback();return NextResponse.json({error:"เฉพาะ Sale Sup หรือ Admin จึงอนุมัติได้"},{status:403});}
      if(!actor.signature_data){await tx.rollback();return NextResponse.json({error:"กรุณาบันทึกภาพลายเซ็นใน Profile ก่อนอนุมัติ"},{status:400});}next="approved";
      if(body.certify!==true){await tx.rollback();return NextResponse.json({error:"กรุณายืนยันการตรวจสอบและรับรองรายงานสำรวจ ราคา เงื่อนไข และผลคำนวณทั้งชุด"},{status:400});}
      if(!q.document_snapshot_json||!q.financial_snapshot_json){await tx.rollback();return NextResponse.json({error:"ไม่พบ Snapshot เอกสาร กรุณาส่งกลับและส่งอนุมัติใหม่"},{status:409});}
      await new sql.Request(tx).input("id",sql.Int,quotationId).input("uid",sql.Int,gate.userId).input("name",sql.NVarChar(150),actor.full_name).input("title",sql.NVarChar(100),actor.job_title||"Sale Supervisor").input("url",sql.NVarChar(500),actor.signature_url||null).input("data",sql.VarBinary(sql.MAX),actor.signature_data).input("mime",sql.NVarChar(100),actor.signature_mime||"image/png").input("note",sql.NVarChar(1000),note||null).query(`UPDATE quotations SET status='approved',approved_by=@uid,approved_at=GETDATE(),approval_certified_by=@uid,approval_certified_at=GETDATE(),approver_name_snapshot=@name,approver_title_snapshot=@title,approver_signature_url_snapshot=@url,approver_signature_data_snapshot=@data,approver_signature_mime_snapshot=@mime,approval_note=@note,updated_by=@uid,updated_at=GETDATE() WHERE id=@id`);
    }else if(action==="changes_required"){
      if(q.status!=="pending_approval"||!actor.roles.some((r:string)=>["admin","sales_sup"].includes(r))){await tx.rollback();return NextResponse.json({error:"ไม่มีสิทธิ์ส่งกลับ"},{status:403});}if(!note){await tx.rollback();return NextResponse.json({error:"กรุณาระบุเหตุผลที่ส่งกลับ"},{status:400});}next="changes_required";
      await new sql.Request(tx).input("id",sql.Int,quotationId).input("uid",sql.Int,gate.userId).input("note",sql.NVarChar(1000),note).query(`UPDATE quotations SET status='changes_required',approval_note=@note,updated_by=@uid,updated_at=GETDATE() WHERE id=@id`);
    }else if(action==="mark_sent"){
      if(q.status!=="approved"){await tx.rollback();return NextResponse.json({error:"ส่งลูกค้าได้เฉพาะใบที่อนุมัติแล้ว"},{status:409});}if(!actor.roles.includes("admin")&&q.assigned_user_id!==gate.userId){await tx.rollback();return NextResponse.json({error:"ส่งได้เฉพาะ Sales เจ้าของ Lead หรือ Admin"},{status:403});}next="approved";
      await new sql.Request(tx).input("id",sql.Int,quotationId).input("uid",sql.Int,gate.userId).query(`UPDATE quotations SET sent_to_customer_by=@uid,sent_to_customer_at=GETDATE(),updated_by=@uid,updated_at=GETDATE() WHERE id=@id`);
      const approved=await new sql.Request(tx).input("lead_id",sql.Int,q.lead_id).query(`SELECT id,doc_no,contract_total_incl_vat FROM quotations WHERE lead_id=@lead_id AND status='approved' ORDER BY option_no`);
      const options=approved.recordset.map((row:{id:number;doc_no:string;contract_total_incl_vat:number})=>({url:`/api/quotation-pdf/${row.id}?user_id=${gate.userId}`,doc_no:row.doc_no,amount:Number(row.contract_total_incl_vat)}));
      const only=options.length===1?options[0]:null;
      await new sql.Request(tx).input("lead_id",sql.Int,q.lead_id).input("files",sql.NVarChar(sql.MAX),JSON.stringify(options)).input("accepted",sql.Int,only?0:null).input("amount",sql.Decimal(12,2),only?.amount??null).input("doc",sql.NVarChar(30),only?.doc_no??null).input("by",sql.NVarChar(200),actor.full_name).input("uid",sql.Int,gate.userId).query(`UPDATE leads SET status='order',quotation_files=@files,quotation_accepted_idx=@accepted,quotation_amount=@amount,quotation_doc_no=@doc,quotation_by=@by,quotation_sent_date=CAST(GETDATE() AS DATE),quote_sent_by=@uid,updated_at=GETDATE() WHERE id=@lead_id`);
    }else{await tx.rollback();return NextResponse.json({error:"action ไม่ถูกต้อง"},{status:400});}
    await new sql.Request(tx).input("qid",sql.Int,quotationId).input("action",sql.NVarChar(30),action).input("from",sql.NVarChar(30),q.status).input("to",sql.NVarChar(30),next).input("note",sql.NVarChar(1000),note||null).input("uid",sql.Int,gate.userId).query(`INSERT quotation_approval_events(quotation_id,action,from_status,to_status,note,acted_by) VALUES(@qid,@action,@from,@to,@note,@uid)`);
    const activityTitle:Record<string,string>={revise:`สร้าง Revision ใหม่จากใบเสนอราคา ${q.doc_no}`,submit:`ส่งใบเสนอราคา ${q.doc_no} ขออนุมัติ`,approve:`อนุมัติใบเสนอราคา ${q.doc_no}`,changes_required:`ส่งใบเสนอราคา ${q.doc_no} กลับแก้ไข`,mark_sent:`ส่งใบเสนอราคา ${q.doc_no} ให้ลูกค้า`};
    await logLeadActivity(tx,{leadId:q.lead_id,activityType:"quotation",title:activityTitle[action]||action,note:note||null,userId:gate.userId});
    await tx.commit();return NextResponse.json({ok:true,status:next,quotation_id:createdRevisionId||quotationId});
  }catch(error){try{await tx.rollback();}catch{}console.error("quotation action",error);return NextResponse.json({error:error instanceof Error?error.message:"ดำเนินการไม่สำเร็จ"},{status:500});}
}
