import {NextRequest,NextResponse} from "next/server";
import {getDb,sql} from "@/lib/db";
import {requireAnyRole} from "@/lib/auth";
import {PACKAGE_EDIT_ROLES} from "@/lib/role-permissions";
// อ่านได้กว้าง — QuotationBuilder ดึงรายการอุปกรณ์มาขึ้นใบเสนอราคา
// (solar_sup เขียนไว้ตรงๆ ถึงจะ inherit solar อยู่แล้ว เพื่อให้อ่านโค้ดแล้วเห็นสิทธิ์ครบ)
export async function GET(req:NextRequest,{params}:{params:Promise<{id:string}>}){const gate=await requireAnyRole(req,["admin","sales","sales_sup","solar","solar_sup"]);if(gate.error)return gate.error;const {id}=await params;const db=await getDb();const r=await db.request().input("pid",sql.Int,Number(id)).query(`SELECT * FROM package_items WHERE package_id=@pid AND is_active=1 ORDER BY sort_order,id`);return NextResponse.json(r.recordset);}
// เขียนได้เฉพาะ admin — เดิมเปิดให้ sales/solar ไว้ ซึ่ง solar_sup ก็ inherit ตามไปด้วย
// ทั้งที่ไม่มี UI ไหนเรียกนอกจากหน้า /packages/manage ที่กดได้เฉพาะ admin อยู่แล้ว
export async function PUT(req:NextRequest,{params}:{params:Promise<{id:string}>}){const gate=await requireAnyRole(req,PACKAGE_EDIT_ROLES);if(gate.error)return gate.error;const {id}=await params;const items=await req.json();if(!Array.isArray(items))return NextResponse.json({error:"items ต้องเป็น array"},{status:400});const db=await getDb();const tx=new sql.Transaction(db);try{await tx.begin();await new sql.Request(tx).input("pid",sql.Int,Number(id)).query(`UPDATE package_items SET is_active=0,updated_at=GETDATE() WHERE package_id=@pid`);let sort=0;for(const item of items.filter(i=>String(i.item_name||"").trim()))await new sql.Request(tx).input("pid",sql.Int,Number(id)).input("name",sql.NVarChar(500),String(item.item_name).trim()).input("qty",sql.Decimal(10,2),Number(item.quantity)||1).input("unit",sql.NVarChar(50),typeof item.unit==="string"&&item.unit.trim()?item.unit.trim():null).input("sort",sql.Int,sort++).query(`INSERT package_items(package_id,item_name,quantity,unit,sort_order) VALUES(@pid,@name,@qty,@unit,@sort)`);await tx.commit();return NextResponse.json({ok:true});}catch(e){try{await tx.rollback();}catch{}return NextResponse.json({error:e instanceof Error?e.message:"บันทึกไม่สำเร็จ"},{status:500});}}
