-- Delete spurious "appointment_rescheduled" activity log rows where the title
-- has the form "...<date> → <date>" — same date on both sides, meaning no
-- actual reschedule happened. These were generated by a bug in PATCH
-- /api/leads/[id] where `nextSlot ?? null` collapsed undefined slot values
-- into null, defeating the same-day guard in logApptChange() and tripping the
-- reschedule branch on every PATCH that carried install_date / survey_date.
--
-- Fixed in src/app/api/(lead)/leads/[id]/route.ts (lines 1032, 1039) — this
-- migration cleans up the rows accumulated before that fix.
--
-- Detection heuristic: the substring AFTER " → " (the new date + optional
-- trailing slot) appears at the END of the substring BEFORE " → " (the old
-- date). Legitimate reschedules with a real date change or a real slot
-- change won't match this pattern.

;WITH parsed AS (
  SELECT
    id,
    title,
    LTRIM(RTRIM(LEFT(title, CHARINDEX(N' → ', title) - 1)))                                AS left_part,
    LTRIM(RTRIM(SUBSTRING(title, CHARINDEX(N' → ', title) + 3, LEN(title))))               AS right_part
  FROM dbo.lead_activities
  WHERE activity_type = 'appointment_rescheduled'
    AND CHARINDEX(N' → ', title) > 0
)
DELETE la
FROM dbo.lead_activities la
INNER JOIN parsed p ON p.id = la.id
WHERE LEN(p.right_part) > 0
  AND LEN(p.left_part) >= LEN(p.right_part)
  AND RIGHT(p.left_part, LEN(p.right_part)) = p.right_part;

PRINT 'spurious appointment_rescheduled rows removed';
GO
