-- 135_package_excel_alignment.sql
-- Generated from the approved Solar quotation V0 workbook.
-- Aligns 22 active Package Masters and refreshes only draft quotation snapshots.
SET XACT_ABORT ON;
BEGIN TRANSACTION;
IF EXISTS (SELECT 1 FROM dbo.app_settings WHERE [key]=N'migration_135_package_excel_v0') BEGIN PRINT 'Migration 135 already applied'; COMMIT TRANSACTION; RETURN; END;
IF EXISTS (SELECT 1 FROM dbo.quotations WHERE status=N'draft' AND package_id=26) THROW 50135, 'Draft quotation uses Package 26; resolve it before migration 135.', 1;
IF COL_LENGTH('dbo.packages','installed_kwp') IS NULL ALTER TABLE dbo.packages ADD installed_kwp DECIMAL(6,2) NULL;
IF COL_LENGTH('dbo.packages','panel_count') IS NULL ALTER TABLE dbo.packages ADD panel_count INT NULL;
IF COL_LENGTH('dbo.packages','panel_watt') IS NULL ALTER TABLE dbo.packages ADD panel_watt INT NULL;
IF COL_LENGTH('dbo.packages','inverter_model') IS NULL ALTER TABLE dbo.packages ADD inverter_model NVARCHAR(100) NULL;
IF COL_LENGTH('dbo.packages','battery_model') IS NULL ALTER TABLE dbo.packages ADD battery_model NVARCHAR(150) NULL;
CREATE TABLE #PackageExcel (package_id INT PRIMARY KEY, expected_price DECIMAL(12,2), installed_kwp DECIMAL(6,2) NULL, panel_count INT NULL, panel_watt INT NULL, panel_brand NVARCHAR(100) NULL, inverter_kw DECIMAL(5,1) NULL, inverter_brand NVARCHAR(50) NULL, inverter_model NVARCHAR(100) NULL, battery_model NVARCHAR(150) NULL);
INSERT #PackageExcel(package_id,expected_price,installed_kwp,panel_count,panel_watt,panel_brand,inverter_kw,inverter_brand,inverter_model,battery_model) VALUES
(1,112000,3.84,6,640,N'JINKO',3,N'HUAWEI',N'SUN2000-3KTL-L1',NULL),
(2,139000,5.12,8,640,N'JINKO',5,N'HUAWEI',N'SUN2000-5KTL-L1',NULL),
(3,225000,10,15,640,N'JINKO',10,N'HUAWEI',N'SUN2000-10K-LC0',NULL),
(4,290000,7.68,12,640,N'JINKO',6,N'DEYE',N'SUN-6K-SG04LP1-EU-SM2',N'ZTT 48V200Ah Lithium Battery'),
(5,320000,7.68,12,640,N'JINKO',8,N'DEYE',N'SUN-8K-SG05LP3-EU-SM2',N'ZTT 48V200Ah Lithium Battery'),
(6,386000,10,15,640,N'JINKO',10,N'DEYE',N'SUN-10K-SG05LP1-EU',N'ZTT 48V200Ah Lithium Battery'),
(7,400000,10,15,640,N'JINKO',10,N'DEYE',N'SUN-10K-SG04LP3-EU',N'ZTT 48V200Ah Lithium Battery'),
(17,275000,5.12,8,640,N'JINKO',5,N'DEYE',N'SUN-5K-SG04LP1-EU-SM2',N'ZTT 48V200Ah Lithium Battery'),
(18,145000,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'LUNA2000-7-E1'),
(19,145000,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'LUNA2000-7-E1'),
(20,235000,NULL,NULL,NULL,NULL,NULL,NULL,NULL,N'LUNA2000-14-S1'),
(21,160000,NULL,3,NULL,NULL,NULL,NULL,NULL,N'LUNA2000-7-E1'),
(22,160000,NULL,3,NULL,NULL,NULL,NULL,NULL,N'LUNA2000-7-E1'),
(23,250000,NULL,3,NULL,NULL,NULL,NULL,NULL,N'LUNA2000-14-S1'),
(24,154000,NULL,2,NULL,NULL,NULL,NULL,NULL,N'LUNA2000-7-E1'),
(25,423000,20,32,640,N'JINKO',20,N'HUAWEI',N'SUN2000-20K-MB0',NULL),
(27,154000,NULL,2,NULL,NULL,NULL,NULL,NULL,N'LUNA2000-7-E1'),
(28,13000,NULL,2,NULL,NULL,NULL,NULL,NULL,NULL),
(29,20000,NULL,3,NULL,NULL,NULL,NULL,NULL,NULL),
(30,13000,NULL,2,NULL,NULL,NULL,NULL,NULL,NULL),
(31,20000,NULL,3,NULL,NULL,NULL,NULL,NULL,NULL),
(32,233000,10,15,640,N'JINKO',10,N'HUAWEI',N'SUN2000-10K-MAP0',NULL);
-- Price check relaxed per prod decision (2026-08-04): keep DB prices as-is, do
-- NOT enforce the Excel prices. Prod pkg 4/5/25 carry 300k/325k/426k vs the
-- Excel's 290k/320k/423k; the UPDATE below never writes `price`, so those DB
-- prices are preserved. Validate package IDs only — the spec backfill is keyed
-- by id, so the alignment is still safe.
IF (SELECT COUNT(*) FROM dbo.packages p JOIN #PackageExcel x ON x.package_id=p.id)<>22 THROW 50135, 'Package IDs differ from the approved Excel mapping.', 1;
UPDATE p SET installed_kwp=x.installed_kwp,panel_count=x.panel_count,panel_watt=x.panel_watt,panel_brand=COALESCE(x.panel_brand,p.panel_brand),inverter_kw=CASE WHEN p.has_inverter=1 THEN x.inverter_kw ELSE p.inverter_kw END,inverter_brand=CASE WHEN p.has_inverter=1 THEN x.inverter_brand ELSE p.inverter_brand END,inverter_model=x.inverter_model,battery_model=x.battery_model FROM dbo.packages p JOIN #PackageExcel x ON x.package_id=p.id;
UPDATE dbo.packages SET is_active=0,remark=N'Not present in approved Excel quotation V0' WHERE id=26;
CREATE TABLE #ExcelItems(package_id INT NOT NULL,sort_order INT NOT NULL,item_name NVARCHAR(500) NOT NULL,quantity DECIMAL(10,2) NOT NULL,unit NVARCHAR(50) NULL,PRIMARY KEY(package_id,sort_order));
INSERT #ExcelItems(package_id,sort_order,item_name,quantity,unit) VALUES
(1,0,N'งานจ้างเหมาติดตั้งระบบผลิตไฟฟ้าจากพลังงานแสงอาทิตย์บนหลังคา ขนาดติดตั้งรวม 3.84 kWp',1,N'เฟส'),
(1,1,N'- PV MODULE ยี่ห้อ JINKO หรือ เทียบเท่า มาตรฐาน TIER 1 ขนาด 640 W จำนวน',6,N'แผง'),
(1,2,N'- INVERTER ยี่ห้อ HUAWEI ( MODEL : SUN2000-3KTL-L1 ) หรือ เทียบเท่า จำนวน',1,N'เครื่อง'),
(1,3,N'- CONTROLLER BOX ( AC/DC BOX )',1,N'SET'),
(1,4,N'- MOUNTING AND ACCESSORIES',1,N'SET'),
(1,5,N'- DC SOLAR CABEL AND ACCESSORIES',1,N'SET'),
(1,6,N'- AC CABLE 1 SET AND ACCESSORIES',1,N'SET'),
(1,7,N'- CONDUIT AND WIREWAY AND ACCESSORIES',1,N'SET'),
(1,8,N'- GROUNDING SYSTEM AND ACCESSORIES',1,N'SET'),
(1,9,N'- INSTALL',1,N'SET'),
(1,10,N'- OPERATION AND MAINTENANCE AND ACCESSORIES',1,N'SET'),
(2,0,N'งานจ้างเหมาติดตั้งระบบผลิตไฟฟ้าจากพลังงานแสงอาทิตย์บนหลังคา ขนาดติดตั้งรวม 5.12 kWp',1,N'เฟส'),
(2,1,N'- PV MODULE ยี่ห้อ JINKO หรือ เทียบเท่า มาตรฐาน TIER 1 ขนาด 640 W จำนวน',8,N'แผง'),
(2,2,N'- INVERTER ยี่ห้อ HUAWEI ( MODEL : SUN2000-5KTL-L1 ) หรือ เทียบเท่า จำนวน',1,N'เครื่อง'),
(2,3,N'- CONTROLLER BOX ( AC/DC BOX )',1,N'SET'),
(2,4,N'- MOUNTING AND ACCESSORIES',1,N'SET'),
(2,5,N'- DC SOLAR CABEL AND ACCESSORIES',1,N'SET'),
(2,6,N'- AC CABLE 1 SET AND ACCESSORIES',1,N'SET'),
(2,7,N'- CONDUIT AND WIREWAY AND ACCESSORIES',1,N'SET'),
(2,8,N'- GROUNDING SYSTEM AND ACCESSORIES',1,N'SET'),
(2,9,N'- INSTALL',1,N'SET'),
(2,10,N'- OPERATION AND MAINTENANCE AND ACCESSORIES',1,N'SET'),
(3,0,N'งานจ้างเหมาติดตั้งระบบผลิตไฟฟ้าจากพลังงานแสงอาทิตย์บนหลังคา ขนาดติดตั้งรวม 10 kWp',1,N'เฟส'),
(3,1,N'- PV MODULE ยี่ห้อ JINKO หรือ เทียบเท่า มาตรฐาน TIER 1 ขนาด 640 W จำนวน',15,N'แผง'),
(3,2,N'- INVERTER ยี่ห้อ HUAWEI Solar Inverters ( Model: SUN2000-10K-LC0 ) หรือเทียบเท่า จำนวน',1,N'เครื่อง'),
(3,3,N'- CONTROLLER BOX ( AC/DC BOX )',1,N'SET'),
(3,4,N'- MOUNTING AND ACCESSORIES',1,N'SET'),
(3,5,N'- DC SOLAR CABEL AND ACCESSORIES',1,N'SET'),
(3,6,N'- AC CABLE 1 SET AND ACCESSORIES',1,N'SET'),
(3,7,N'- CONDUIT AND WIREWAY AND ACCESSORIES',1,N'SET'),
(3,8,N'- GROUNDING SYSTEM AND ACCESSORIES',1,N'SET'),
(3,9,N'- INSTALL',1,N'SET'),
(3,10,N'- OPERATION AND MAINTENANCE AND ACCESSORIES',1,N'SET'),
(4,0,N'งานจ้างเหมาติดตั้งระบบผลิตไฟฟ้าจากพลังงานแสงอาทิตย์บนหลังคา ขนาดติดตั้งรวม 7.68 kWp',1,N'เฟส'),
(4,1,N'- PV MODULE ยี่ห้อ JINKO หรือ เทียบเท่า มาตรฐาน TIER 1 ขนาด 640 W จำนวน',12,N'แผง'),
(4,2,N'- INVERTER ยี่ห้อ DEYE ( MODEL : SUN-6K-SG04LP1-EU-SM2 ) หรือเทียบเท่า จำนวน',1,N'เครื่อง'),
(4,3,N'- BATTERY  MODULE ยี่ห้อ ZTT ( ZTT 48V200Ah Lithium Battery ) ขนาด 9.6 kWh  หรือเทียบเท่า จำนวน',1,N'SET'),
(4,4,N'- CONTROLLER BOX ( AC/DC BOX )',1,N'SET'),
(4,5,N'- MOUNTING AND ACCESSORIES',1,N'SET'),
(4,6,N'- DC SOLAR CABEL AND ACCESSORIES',1,N'SET'),
(4,7,N'- AC CABLE 1 SET AND ACCESSORIES',1,N'SET'),
(4,8,N'- CONDUIT AND WIREWAY AND ACCESSORIES',1,N'SET'),
(4,9,N'- GROUNDING SYSTEM AND ACCESSORIES',1,N'SET'),
(4,10,N'- INSTALL',1,N'SET'),
(4,11,N'- OPERATION AND MAINTENANCE AND ACCESSORIES',1,N'SET'),
(5,0,N'งานจ้างเหมาติดตั้งระบบผลิตไฟฟ้าจากพลังงานแสงอาทิตย์บนหลังคา ขนาดติดตั้งรวม 7.68 kWp',3,N'เฟส'),
(5,1,N'- PV MODULE ยี่ห้อ JINKO หรือ เทียบเท่า มาตรฐาน TIER 1 ขนาด 640 W จำนวน',12,N'แผง'),
(5,2,N'- INVERTER ยี่ห้อ DEYE ( MODEL : SUN-8K-SG05LP3-EU-SM2 ) หรือเทียบเท่า จำนวน',1,N'เครื่อง'),
(5,3,N'- BATTERY  MODULE ยี่ห้อ ZTT ( ZTT 48V200Ah Lithium Battery ) ขนาด 9.6 kWh  หรือเทียบเท่า จำนวน',1,N'SET'),
(5,4,N'- CONTROLLER BOX ( AC/DC BOX )',1,N'SET'),
(5,5,N'- MOUNTING AND ACCESSORIES',1,N'SET'),
(5,6,N'- DC SOLAR CABEL AND ACCESSORIES',1,N'SET'),
(5,7,N'- AC CABLE 1 SET AND ACCESSORIES',1,N'SET'),
(5,8,N'- CONDUIT AND WIREWAY AND ACCESSORIES',1,N'SET'),
(5,9,N'- GROUNDING SYSTEM AND ACCESSORIES',1,N'SET'),
(5,10,N'- INSTALL',1,N'SET'),
(5,11,N'- OPERATION AND MAINTENANCE AND ACCESSORIES',1,N'SET'),
(6,0,N'งานจ้างเหมาติดตั้งระบบผลิตไฟฟ้าจากพลังงานแสงอาทิตย์บนหลังคา ขนาดติดตั้งรวม 10 kWp',1,N'เฟส'),
(6,1,N'- PV MODULE ยี่ห้อ JINKO หรือ เทียบเท่า มาตรฐาน TIER 1 ขนาด 640 W จำนวน',15,N'แผง'),
(6,2,N'- INVERTER ยี่ห้อ DEYE ( MODEL : SUN-10K-SG05LP1-EU ) หรือเทียบเท่า จำนวน',1,N'เครื่อง'),
(6,3,N'- BATTERY  MODULE ยี่ห้อ ZTT ( ZTT 48V200Ah Lithium Battery ) ขนาด 9.6 kWh  หรือเทียบเท่า จำนวน',1,N'SET'),
(6,4,N'- CONTROLLER BOX ( AC/DC BOX )',1,N'SET'),
(6,5,N'- MOUNTING AND ACCESSORIES',1,N'SET'),
(6,6,N'- DC SOLAR CABEL AND ACCESSORIES',1,N'SET'),
(6,7,N'- AC CABLE 1 SET AND ACCESSORIES',1,N'SET'),
(6,8,N'- CONDUIT AND WIREWAY AND ACCESSORIES',1,N'SET'),
(6,9,N'- GROUNDING SYSTEM AND ACCESSORIES',1,N'SET'),
(6,10,N'- INSTALL',1,N'SET'),
(6,11,N'- OPERATION AND MAINTENANCE AND ACCESSORIES',1,N'SET'),
(7,0,N'งานจ้างเหมาติดตั้งระบบผลิตไฟฟ้าจากพลังงานแสงอาทิตย์บนหลังคา ขนาดติดตั้งรวม 10 kWp',3,N'เฟส'),
(7,1,N'- PV MODULE ยี่ห้อ JINKO หรือ เทียบเท่า มาตรฐาน TIER 1 ขนาด 640 W จำนวน',15,N'แผง'),
(7,2,N'- INVERTER ยี่ห้อ DEYE ( MODEL : SUN-10K-SG04LP3-EU ) หรือเทียบเท่า จำนวน',1,N'เครื่อง'),
(7,3,N'- BATTERY  MODULE ยี่ห้อ ZTT ( ZTT 48V200Ah Lithium Battery ) ขนาด 9.6 kWh  หรือเทียบเท่า จำนวน',1,N'SET'),
(7,4,N'- CONTROLLER BOX ( AC/DC BOX )',1,N'SET'),
(7,5,N'- MOUNTING AND ACCESSORIES',1,N'SET'),
(7,6,N'- DC SOLAR CABEL AND ACCESSORIES',1,N'SET'),
(7,7,N'- AC CABLE 1 SET AND ACCESSORIES',1,N'SET'),
(7,8,N'- CONDUIT AND WIREWAY AND ACCESSORIES',1,N'SET'),
(7,9,N'- GROUNDING SYSTEM AND ACCESSORIES',1,N'SET'),
(7,10,N'- INSTALL',1,N'SET'),
(7,11,N'- OPERATION AND MAINTENANCE AND ACCESSORIES',1,N'SET'),
(17,0,N'งานจ้างเหมาติดตั้งระบบผลิตไฟฟ้าจากพลังงานแสงอาทิตย์บนหลังคา ขนาดติดตั้งรวม 5.12 kWp',1,N'เฟส'),
(17,1,N'- PV MODULE ยี่ห้อ JINKO หรือ เทียบเท่า มาตรฐาน TIER 1 ขนาด 640 W จำนวน',8,N'แผง'),
(17,2,N'- INVERTER ยี่ห้อ DEYE ( MODEL : SUN-5K-SG04LP1-EU-SM2 ) หรือเทียบเท่า จำนวน',1,N'เครื่อง'),
(17,3,N'- BATTERY  MODULE ยี่ห้อ ZTT ( ZTT 48V200Ah Lithium Battery ) ขนาด 9.6 kWh  หรือเทียบเท่า จำนวน',1,N'SET'),
(17,4,N'- CONTROLLER BOX ( AC/DC BOX )',1,N'SET'),
(17,5,N'- MOUNTING AND ACCESSORIES',1,N'SET'),
(17,6,N'- DC SOLAR CABEL AND ACCESSORIES',1,N'SET'),
(17,7,N'- AC CABLE 1 SET AND ACCESSORIES',1,N'SET'),
(17,8,N'- CONDUIT AND WIREWAY AND ACCESSORIES',1,N'SET'),
(17,9,N'- GROUNDING SYSTEM AND ACCESSORIES',1,N'SET'),
(17,10,N'- INSTALL',1,N'SET'),
(17,11,N'- OPERATION AND MAINTENANCE AND ACCESSORIES',1,N'SET'),
(18,0,N'งานจ้างเหมาติดตั้งระบบแบตเตอรี่ ขนาดติดตั้ง แบตเตอรี่ 7 kWh (ระบบเดิม 3 kWp)',1,NULL),
(18,1,N'- HUAWEI POWER MODULE, LUNA2000-10KW-C1 (10 YEARS WARRANTY)',1,N'SET'),
(18,2,N'- HUAWEI BATTERY MODULE, LUNA2000-7-E1 (10 YEARS WARRANTY)',1,N'SET'),
(18,3,N'- MOUNTING AND ACCESSORIES',1,N'SET'),
(18,4,N'- CONDUIT AND WIREWAY AND ACCESSORIES',1,N'SET'),
(18,5,N'- DC SOLAR CABEL AND ACCESSORIES',1,N'SET'),
(18,6,N'- AC CABLE 1 SET AND ACCESSORIES',1,N'SET'),
(18,7,N'- INSTALL',1,N'SET'),
(18,8,N'- OPERATION AND ACCESSORIES',1,N'SET'),
(19,0,N'งานจ้างเหมาติดตั้งระบบแบตเตอรี่ ขนาดติดตั้ง แบตเตอรี่ 7 kWh (ระบบเดิม 5 kWp)',1,NULL),
(19,1,N'- HUAWEI POWER MODULE, LUNA2000-10KW-C1 (10 YEARS WARRANTY)',1,N'SET'),
(19,2,N'- HUAWEI BATTERY MODULE, LUNA2000-7-E1 (10 YEARS WARRANTY)',1,N'SET'),
(19,3,N'- MOUNTING AND ACCESSORIES',1,N'SET'),
(19,4,N'- CONDUIT AND WIREWAY AND ACCESSORIES',1,N'SET'),
(19,5,N'- DC SOLAR CABEL AND ACCESSORIES',1,N'SET'),
(19,6,N'- AC CABLE 1 SET AND ACCESSORIES',1,N'SET'),
(19,7,N'- INSTALL',1,N'SET'),
(19,8,N'- OPERATION AND ACCESSORIES',1,N'SET'),
(20,0,N'งานจ้างเหมาติดตั้งระบบแบตเตอรี่ ขนาดติดตั้ง แบตเตอรี่ 14 kWh (ระบบเดิม 5 kWp)',1,NULL),
(20,1,N'- HUAWEI POWER MODULE, LUNA2000-10KW-C1 (10 YEARS WARRANTY)',1,N'SET'),
(20,2,N'- HUAWEI BATTERY MODULE, LUNA2000-14-S1 (10 YEARS WARRANTY)',1,N'SET'),
(20,3,N'- MOUNTING AND ACCESSORIES',1,N'SET'),
(20,4,N'- CONDUIT AND WIREWAY AND ACCESSORIES',1,N'SET'),
(20,5,N'- DC SOLAR CABEL AND ACCESSORIES',1,N'SET'),
(20,6,N'- AC CABLE 1 SET AND ACCESSORIES',1,N'SET'),
(20,7,N'- INSTALL',1,N'SET'),
(20,8,N'- OPERATION AND ACCESSORIES',1,N'SET'),
(21,0,N'งานจ้างเหมาติดตั้งระบบแบตเตอรี่ ขนาดติดตั้ง แบตเตอรี่ 7 kWh (ระบบเดิม 3 kWp)',1,NULL),
(21,1,N'- HUAWEI POWER MODULE, LUNA2000-10KW-C1 (10 YEARS WARRANTY)',1,N'SET'),
(21,2,N'- HUAWEI BATTERY MODULE, LUNA2000-7-E1 (10 YEARS WARRANTY)',1,N'SET'),
(21,3,N'PV MODULE ยี่ห้อ JINKO หรือ เทียบเท่า มาตรฐาน TIER 1 ขนาด 640 W จำนวน',3,N'แผง'),
(21,4,N'- MOUNTING AND ACCESSORIES',1,N'SET'),
(21,5,N'- CONDUIT AND WIREWAY AND ACCESSORIES',1,N'SET'),
(21,6,N'- DC SOLAR CABEL AND ACCESSORIES',1,N'SET'),
(21,7,N'- AC CABLE 1 SET AND ACCESSORIES',1,N'SET'),
(21,8,N'- INSTALL',1,N'SET'),
(21,9,N'- OPERATION AND ACCESSORIES',1,N'SET'),
(22,0,N'งานจ้างเหมาติดตั้งระบบแบตเตอรี่ ขนาดติดตั้ง แบตเตอรี่ 7 kWh (ระบบเดิม 5 kWp)',1,NULL),
(22,1,N'- HUAWEI POWER MODULE, LUNA2000-10KW-C1 (10 YEARS WARRANTY)',1,N'SET'),
(22,2,N'- HUAWEI BATTERY MODULE, LUNA2000-7-E1 (10 YEARS WARRANTY)',1,N'SET'),
(22,3,N'PV MODULE ยี่ห้อ JINKO หรือ เทียบเท่า มาตรฐาน TIER 1 ขนาด 640 W จำนวน',3,N'แผง'),
(22,4,N'- MOUNTING AND ACCESSORIES',1,N'SET'),
(22,5,N'- CONDUIT AND WIREWAY AND ACCESSORIES',1,N'SET'),
(22,6,N'- DC SOLAR CABEL AND ACCESSORIES',1,N'SET'),
(22,7,N'- AC CABLE 1 SET AND ACCESSORIES',1,N'SET'),
(22,8,N'- INSTALL',1,N'SET'),
(22,9,N'- OPERATION AND ACCESSORIES',1,N'SET'),
(23,0,N'งานจ้างเหมาติดตั้งระบบแบตเตอรี่ ขนาดติดตั้ง แบตเตอรี่ 14 kWh (ระบบเดิม 5 kWp)',1,NULL),
(23,1,N'- HUAWEI POWER MODULE, LUNA2000-10KW-C1 (10 YEARS WARRANTY)',1,N'SET'),
(23,2,N'- HUAWEI BATTERY MODULE, LUNA2000-14-S1 (10 YEARS WARRANTY)',1,N'SET'),
(23,3,N'PV MODULE ยี่ห้อ JINKO หรือ เทียบเท่า มาตรฐาน TIER 1 ขนาด 640 W จำนวน',3,N'แผง'),
(23,4,N'- MOUNTING AND ACCESSORIES',1,N'SET'),
(23,5,N'- CONDUIT AND WIREWAY AND ACCESSORIES',1,N'SET'),
(23,6,N'- DC SOLAR CABEL AND ACCESSORIES',1,N'SET'),
(23,7,N'- AC CABLE 1 SET AND ACCESSORIES',1,N'SET'),
(23,8,N'- INSTALL',1,N'SET'),
(23,9,N'- OPERATION AND ACCESSORIES',1,N'SET'),
(24,0,N'งานจ้างเหมาติดตั้งระบบแบตเตอรี่ ขนาดติดตั้ง แบตเตอรี่ 7 kWh (ระบบเดิม 3 kWp)',1,NULL),
(24,1,N'- HUAWEI POWER MODULE, LUNA2000-10KW-C1 (10 YEARS WARRANTY)',1,N'SET'),
(24,2,N'- HUAWEI BATTERY MODULE, LUNA2000-7-E1 (10 YEARS WARRANTY)',1,N'SET'),
(24,3,N'PV MODULE ยี่ห้อ JINKO หรือ เทียบเท่า มาตรฐาน TIER 1 ขนาด 640 W จำนวน',2,N'แผง'),
(24,4,N'- MOUNTING AND ACCESSORIES',1,N'SET'),
(24,5,N'- CONDUIT AND WIREWAY AND ACCESSORIES',1,N'SET'),
(24,6,N'- DC SOLAR CABEL AND ACCESSORIES',1,N'SET'),
(24,7,N'- AC CABLE 1 SET AND ACCESSORIES',1,N'SET'),
(24,8,N'- INSTALL',1,N'SET'),
(24,9,N'- OPERATION AND ACCESSORIES',1,N'SET'),
(25,0,N'งานจ้างเหมาติดตั้งระบบผลิตไฟฟ้าจากพลังงานแสงอาทิตย์บนหลังคา ขนาดติดตั้งรวม 20 kWp',3,N'เฟส'),
(25,1,N'- PV MODULE ยี่ห้อ JINKO หรือ เทียบเท่า มาตรฐาน TIER 1 ขนาด 640 W จำนวน',32,N'แผง'),
(25,2,N'- INVERTER ยี่ห้อ HUAWEI Solar Inverters ( Model: SUN2000-20K-MB0 ) หรือเทียบเท่า จำนวน',1,N'เครื่อง'),
(25,3,N'- CONTROLLER BOX ( AC/DC BOX )',1,N'SET'),
(25,4,N'- MOUNTING AND ACCESSORIES',1,N'SET'),
(25,5,N'- DC SOLAR CABEL AND ACCESSORIES',1,N'SET'),
(25,6,N'- AC CABLE 1 SET AND ACCESSORIES',1,N'SET'),
(25,7,N'- CONDUIT AND WIREWAY AND ACCESSORIES',1,N'SET'),
(25,8,N'- GROUNDING SYSTEM AND ACCESSORIES',1,N'SET'),
(25,9,N'- INSTALL',1,N'SET'),
(25,10,N'- OPERATION AND MAINTENANCE AND ACCESSORIES',1,N'SET'),
(27,0,N'งานจ้างเหมาติดตั้งระบบแบตเตอรี่ ขนาดติดตั้ง แบตเตอรี่ 7 kWh (ระบบเดิม 5 kWp)',1,NULL),
(27,1,N'- HUAWEI POWER MODULE, LUNA2000-10KW-C1 (10 YEARS WARRANTY)',1,N'SET'),
(27,2,N'- HUAWEI BATTERY MODULE, LUNA2000-7-E1 (10 YEARS WARRANTY)',1,N'SET'),
(27,3,N'PV MODULE ยี่ห้อ JINKO หรือ เทียบเท่า มาตรฐาน TIER 1 ขนาด 640 W จำนวน',2,N'แผง'),
(27,4,N'- MOUNTING AND ACCESSORIES',1,N'SET'),
(27,5,N'- CONDUIT AND WIREWAY AND ACCESSORIES',1,N'SET'),
(27,6,N'- DC SOLAR CABEL AND ACCESSORIES',1,N'SET'),
(27,7,N'- AC CABLE 1 SET AND ACCESSORIES',1,N'SET'),
(27,8,N'- INSTALL',1,N'SET'),
(27,9,N'- OPERATION AND ACCESSORIES',1,N'SET'),
(28,0,N'งานจ้างเหมาติดตั้งเพิ่มแผงโซลาร์เซลล์ (ระบบเดิม 3 kWp)',1,NULL),
(28,1,N'PV MODULE ยี่ห้อ JINKO หรือ เทียบเท่า มาตรฐาน TIER 1 ขนาด 640 W จำนวน',2,N'แผง'),
(28,2,N'- MOUNTING AND ACCESSORIES',1,N'SET'),
(28,3,N'- INSTALL',1,N'SET'),
(28,4,N'- OPERATION AND ACCESSORIES',1,N'SET'),
(29,0,N'งานจ้างเหมาติดตั้งเพิ่มแผงโซลาร์เซลล์ (ระบบเดิม 3 kWp)',1,NULL),
(29,1,N'PV MODULE ยี่ห้อ JINKO หรือ เทียบเท่า มาตรฐาน TIER 1 ขนาด 640 W จำนวน',3,N'แผง'),
(29,2,N'- MOUNTING AND ACCESSORIES',1,N'SET'),
(29,3,N'- INSTALL',1,N'SET'),
(29,4,N'- OPERATION AND ACCESSORIES',1,N'SET'),
(30,0,N'งานจ้างเหมาติดตั้งเพิ่มแผงโซลาร์เซลล์ (ระบบเดิม 5 kWp)',1,NULL),
(30,1,N'PV MODULE ยี่ห้อ JINKO หรือ เทียบเท่า มาตรฐาน TIER 1 ขนาด 640 W จำนวน',2,N'แผง'),
(30,2,N'- MOUNTING AND ACCESSORIES',1,N'SET'),
(30,3,N'- INSTALL',1,N'SET'),
(30,4,N'- OPERATION AND ACCESSORIES',1,N'SET'),
(31,0,N'งานจ้างเหมาติดตั้งเพิ่มแผงโซลาร์เซลล์ (ระบบเดิม 5 kWp)',1,NULL),
(31,1,N'PV MODULE ยี่ห้อ JINKO หรือ เทียบเท่า มาตรฐาน TIER 1 ขนาด 640 W จำนวน',3,N'แผง'),
(31,2,N'- MOUNTING AND ACCESSORIES',1,N'SET'),
(31,3,N'- INSTALL',1,N'SET'),
(31,4,N'- OPERATION AND ACCESSORIES',1,N'SET'),
(32,0,N'งานจ้างเหมาติดตั้งระบบผลิตไฟฟ้าจากพลังงานแสงอาทิตย์บนหลังคา ขนาดติดตั้งรวม 10 kWp',3,N'เฟส'),
(32,1,N'- PV MODULE ยี่ห้อ JINKO หรือ เทียบเท่า มาตรฐาน TIER 1 ขนาด 640 W จำนวน',15,N'แผง'),
(32,2,N'- INVERTER ยี่ห้อ HUAWEI Solar Inverters ( Model: SUN2000-10K-MAP0 ) หรือเทียบเท่า จำนวน',1,N'เครื่อง'),
(32,3,N'- CONTROLLER BOX ( AC/DC BOX )',1,N'SET'),
(32,4,N'- MOUNTING AND ACCESSORIES',1,N'SET'),
(32,5,N'- DC SOLAR CABEL AND ACCESSORIES',1,N'SET'),
(32,6,N'- AC CABLE 1 SET AND ACCESSORIES',1,N'SET'),
(32,7,N'- CONDUIT AND WIREWAY AND ACCESSORIES',1,N'SET'),
(32,8,N'- GROUNDING SYSTEM AND ACCESSORIES',1,N'SET'),
(32,9,N'- INSTALL',1,N'SET'),
(32,10,N'- OPERATION AND MAINTENANCE AND ACCESSORIES',1,N'SET');
UPDATE pi SET is_active=0,updated_at=GETDATE() FROM dbo.package_items pi JOIN #PackageExcel x ON x.package_id=pi.package_id WHERE pi.is_active=1;
INSERT dbo.package_items(package_id,item_name,quantity,unit,sort_order,is_active) SELECT package_id,item_name,quantity,unit,sort_order,1 FROM #ExcelItems ORDER BY package_id,sort_order;
UPDATE q SET package_name_snapshot=p.name,package_price_snapshot=p.price,document_snapshot_json=NULL,financial_snapshot_json=NULL,document_snapshot_at=NULL,updated_at=GETDATE() FROM dbo.quotations q JOIN dbo.packages p ON p.id=q.package_id WHERE q.status=N'draft';
DELETE a FROM dbo.quotation_document_artifacts a JOIN dbo.quotations q ON q.id=a.quotation_id WHERE q.status=N'draft';
DELETE qi FROM dbo.quotation_items qi JOIN dbo.quotations q ON q.id=qi.quotation_id WHERE q.status=N'draft' AND qi.source_type=N'package';
INSERT dbo.quotation_items(quotation_id,source_type,package_item_id,item_name_snapshot,quantity,unit,unit_price,line_total,sort_order) SELECT q.id,N'package',pi.id,pi.item_name,pi.quantity,pi.unit,0,0,pi.sort_order FROM dbo.quotations q JOIN dbo.package_items pi ON pi.package_id=q.package_id AND pi.is_active=1 WHERE q.status=N'draft';
;WITH ranked AS (SELECT qi.id,ROW_NUMBER() OVER(PARTITION BY qi.quotation_id ORDER BY qi.sort_order,qi.id)-1 rn,c.cnt FROM dbo.quotation_items qi JOIN dbo.quotations q ON q.id=qi.quotation_id CROSS APPLY (SELECT COUNT(*) cnt FROM dbo.quotation_items pqi WHERE pqi.quotation_id=qi.quotation_id AND pqi.source_type=N'package') c WHERE q.status=N'draft' AND qi.source_type<>N'package') UPDATE qi SET sort_order=ranked.cnt+ranked.rn FROM dbo.quotation_items qi JOIN ranked ON ranked.id=qi.id;
INSERT dbo.app_settings([key],value,updated_at) VALUES(N'migration_135_package_excel_v0',N'2026-08-04; source=Solar quotation V0 workbook; packages=22; draft_refresh=automatic',GETDATE());
COMMIT TRANSACTION;
